const debugArr = {
    page_name: "主页",
page_height: 1024,
page_width: 1440,
num: 15,
controlsArr: [
    {
        "num": 0,
        "color": null,
        "delSeen": false,
        "seen": false,
        "opacity": 100,
        "borderExists": true,
        "border": "",
        "borderWidth": 1,
        "pic": 0,
        "word": false,
        "z_index": 0,
        "w": 10,
        "h": 10,
        "dragging": "onDrag",
        "resizing": "onResize",
        "parent": true,
        "class": "init",
        "handles": [
            "tl",
            "tr",
            "bl",
            "br"
        ],
        "editingUsers": {},
        "lock": {}
    },
    {
        "num": 1,
        "color": "#898989",
        "btn": false,
        "borderRadius": 0,
        "tag": false,
        "fontsize": 14,
        "fontWeight": 400,
        "borderColor": "#929292",
        "link": false,
        "step": false,
        "sem": false,
        "cnt": false,
        "textColor": "black",
        "swi": false,
        "pag": false,
        "scr": false,
        "web": false,
        "sli": false,
        "seen": true,
        "sc": false,
        "mc": false,
        "sel": false,
        "top": "10px",
        "left": "10px",
        "opacity": 100,
        "delSeen": false,
        "borderExists": false,
        "border": "none",
        "word": false,
        "borderWidth": 1,
        "z_index": 0,
        "pic": 0,
        "w": 848,
        "h": 1,
        "x": 1,
        "y": 55,
        "dragging": "onDrag",
        "resizing": "onResize",
        "parent": true,
        "class": "square",
        "handles": [
            "tl",
            "tr",
            "bl",
            "br"
        ],
        "editingUsers": {
            "72": {
                "username": "Rui",
                "isEdit": false
            }
        },
        "lock": {}
    },
    {
        "num": 2,
        "color": null,
        "btn": false,
        "borderRadius": 0,
        "tag": false,
        "fontsize": 14,
        "fontWeight": 400,
        "borderColor": "black",
        "link": false,
        "step": false,
        "sem": false,
        "cnt": false,
        "textColor": "black",
        "swi": false,
        "pag": false,
        "scr": false,
        "web": false,
        "sli": false,
        "seen": false,
        "sc": false,
        "mc": false,
        "sel": false,
        "top": "10px",
        "left": "10px",
        "opacity": 100,
        "delSeen": false,
        "borderExists": true,
        "border": "rgb(143, 143, 143) solid 1px",
        "word": false,
        "borderWidth": 1,
        "z_index": 1,
        "pic": 0,
        "w": 254,
        "h": 124,
        "x": 260,
        "y": 325,
        "dragging": "onDrag",
        "resizing": "onResize",
        "parent": true,
        "class": "square",
        "handles": [
            "tl",
            "tr",
            "bl",
            "br"
        ],
        "editingUsers": {
            "72": {
                "username": "Rui",
                "isEdit": false
            }
        },
        "lock": {}
    },
    {
        "num": 3,
        "color": null,
        "textColor": "#000000",
        "fontWeight": 800,
        "borderRadius": 0,
        "seen": true,
        "borderColor": "black",
        "top": "10px",
        "link": false,
        "sem": false,
        "fontsize": 22,
        "cnt": false,
        "step": false,
        "pag": false,
        "web": false,
        "tag": false,
        "sli": false,
        "swi": false,
        "sc": false,
        "scr": false,
        "mc": false,
        "sel": false,
        "left": "10px",
        "opacity": 100,
        "btn": false,
        "delSeen": false,
        "borderExists": false,
        "border": "none",
        "borderWidth": 1,
        "word": true,
        "text": "Logo",
        "z_index": 2,
        "w": 120,
        "h": 28,
        "x": 69,
        "y": 15,
        "dragging": "onDrag",
        "resizing": "onResize",
        "parent": true,
        "class": "word",
        "handles": [
            "tl",
            "tr",
            "bl",
            "br"
        ],
        "editingUsers": {
            "72": {
                "username": "Rui",
                "isEdit": false
            }
        },
        "lock": {}
    },
    {
        "num": 4,
        "color": "transparent",
        "textColor": "black",
        "seen": true,
        "fontWeight": 400,
        "borderColor": "black",
        "cnt": false,
        "borderRadius": 2,
        "link": false,
        "step": false,
        "fontsize": 14,
        "sem": false,
        "value": "",
        "top": "10px",
        "tag": false,
        "pag": false,
        "sli": false,
        "web": false,
        "swi": false,
        "sc": false,
        "scr": false,
        "mc": false,
        "left": "10px",
        "opacity": 100,
        "sel": true,
        "delSeen": false,
        "borderExists": true,
        "border": "rgb(143, 143, 143) solid 1px",
        "borderWidth": 1,
        "word": false,
        "btn": false,
        "text": "",
        "z_index": 3,
        "w": 196,
        "h": 34,
        "x": 517,
        "y": 12,
        "dragging": "onDrag",
        "resizing": "onResize",
        "parent": true,
        "class": "sel",
        "handles": [
            "tl",
            "tr",
            "bl",
            "br"
        ],
        "editingUsers": {
            "72": {
                "username": "Rui",
                "isEdit": false
            }
        },
        "lock": {}
    },
    {
        "num": 5,
        "color": null,
        "textColor": "black",
        "fontWeight": 400,
        "borderRadius": 0,
        "seen": true,
        "borderColor": "black",
        "top": "10px",
        "link": false,
        "sem": false,
        "fontsize": 16,
        "cnt": false,
        "step": false,
        "pag": false,
        "web": false,
        "tag": false,
        "sli": false,
        "swi": false,
        "sc": false,
        "scr": false,
        "mc": false,
        "sel": false,
        "left": "10px",
        "opacity": 100,
        "btn": false,
        "delSeen": false,
        "borderExists": false,
        "border": "none",
        "borderWidth": 1,
        "word": true,
        "text": "请选择",
        "z_index": 4,
        "w": 120,
        "h": 28,
        "x": 530,
        "y": 20,
        "dragging": "onDrag",
        "resizing": "onResize",
        "parent": true,
        "class": "word",
        "handles": [
            "tl",
            "tr",
            "bl",
            "br"
        ],
        "editingUsers": {
            "72": {
                "username": "Rui",
                "isEdit": false
            }
        },
        "lock": {}
    },
    {
        "num": 6,
        "color": "#83D7BA",
        "textColor": "#FFFFFF",
        "seen": true,
        "borderRadius": 6,
        "borderColor": "#595959",
        "fontWeight": 400,
        "sem": false,
        "step": false,
        "link": false,
        "content": "登录",
        "top": "10px",
        "pag": false,
        "cnt": false,
        "fontsize": 14,
        "tag": false,
        "sli": false,
        "swi": false,
        "sc": false,
        "web": false,
        "scr": false,
        "mc": false,
        "sel": false,
        "left": "10px",
        "opacity": 100,
        "delSeen": false,
        "borderExists": true,
        "border": "rgb(143, 143, 143) solid 1px",
        "borderWidth": 1,
        "word": false,
        "btn": true,
        "text": "",
        "z_index": 5,
        "w": 50,
        "h": 30,
        "x": 736,
        "y": 14,
        "dragging": "onDrag",
        "resizing": "onResize",
        "parent": true,
        "class": "btn",
        "handles": [
            "tl",
            "tr",
            "bl",
            "br"
        ],
        "editingUsers": {
            "72": {
                "username": "Rui",
                "isEdit": false
            }
        },
        "lock": {}
    },
    {
        "num": 7,
        "color": "rgba(250, 250, 250, 0.781)",
        "textColor": "black",
        "fontWeight": 800,
        "borderRadius": 0,
        "seen": true,
        "borderColor": "black",
        "top": "10px",
        "link": false,
        "sem": false,
        "fontsize": 40,
        "cnt": false,
        "step": false,
        "pag": false,
        "web": false,
        "tag": false,
        "sli": false,
        "swi": false,
        "sc": false,
        "scr": false,
        "mc": false,
        "sel": false,
        "left": "10px",
        "opacity": 100,
        "btn": false,
        "delSeen": false,
        "borderExists": false,
        "border": "none",
        "borderWidth": 1,
        "word": true,
        "text": "学术成果分享平台",
        "z_index": 6,
        "w": 336,
        "h": 49,
        "x": 264,
        "y": 134,
        "dragging": "onDrag",
        "resizing": "onResize",
        "parent": true,
        "class": "word",
        "handles": [
            "tl",
            "tr",
            "bl",
            "br"
        ],
        "editingUsers": {
            "72": {
                "username": "Rui",
                "isEdit": false
            }
        },
        "lock": {}
    },
    {
        "num": 8,
        "color": null,
        "textColor": "#737373",
        "fontWeight": 400,
        "borderRadius": 0,
        "seen": true,
        "borderColor": "black",
        "top": "10px",
        "link": false,
        "sem": false,
        "fontsize": 18,
        "cnt": false,
        "step": false,
        "pag": false,
        "web": false,
        "tag": false,
        "sli": false,
        "swi": false,
        "sc": false,
        "scr": false,
        "mc": false,
        "sel": false,
        "left": "10px",
        "opacity": 100,
        "btn": false,
        "delSeen": false,
        "borderExists": false,
        "border": "none",
        "borderWidth": 1,
        "word": true,
        "text": "Platform for sharing academic achievements",
        "z_index": 7,
        "w": 393,
        "h": 30,
        "x": 236,
        "y": 193,
        "dragging": "onDrag",
        "resizing": "onResize",
        "parent": true,
        "class": "word",
        "handles": [
            "tl",
            "tr",
            "bl",
            "br"
        ],
        "editingUsers": {
            "72": {
                "username": "Rui",
                "isEdit": false
            }
        },
        "lock": {}
    },
    {
        "num": 9,
        "color": "#fff",
        "btn": false,
        "borderRadius": 0,
        "tag": false,
        "fontsize": 14,
        "fontWeight": 400,
        "borderColor": "#5C5C5C",
        "link": false,
        "step": false,
        "sem": false,
        "cnt": false,
        "textColor": "black",
        "swi": false,
        "pag": false,
        "scr": false,
        "web": false,
        "sli": false,
        "seen": true,
        "sc": false,
        "mc": false,
        "sel": false,
        "top": "10px",
        "left": "10px",
        "opacity": 100,
        "delSeen": false,
        "borderExists": true,
        "border": "",
        "word": false,
        "borderWidth": 1,
        "z_index": 8,
        "pic": 0,
        "w": 190,
        "h": 230,
        "x": 110,
        "y": 260,
        "dragging": "onDrag",
        "resizing": "onResize",
        "parent": true,
        "class": "square",
        "handles": [
            "tl",
            "tr",
            "bl",
            "br"
        ],
        "editingUsers": {
            "72": {
                "username": "Rui",
                "isEdit": false
            }
        },
        "lock": {}
    },
    {
        "num": 10,
        "color": "#fff",
        "btn": false,
        "borderRadius": 0,
        "tag": false,
        "fontsize": 14,
        "fontWeight": 400,
        "borderColor": "#5C5C5C",
        "link": false,
        "step": false,
        "sem": false,
        "cnt": false,
        "textColor": "black",
        "swi": false,
        "pag": false,
        "scr": false,
        "web": false,
        "sli": false,
        "seen": true,
        "sc": false,
        "mc": false,
        "sel": false,
        "top": "10px",
        "left": "10px",
        "opacity": 100,
        "delSeen": false,
        "borderExists": true,
        "border": "",
        "word": false,
        "borderWidth": 1,
        "z_index": 9,
        "pic": 0,
        "w": 190,
        "h": 230,
        "x": 340,
        "y": 260,
        "dragging": "onDrag",
        "resizing": "onResize",
        "parent": true,
        "class": "square",
        "handles": [
            "tl",
            "tr",
            "bl",
            "br"
        ],
        "editingUsers": {
            "72": {
                "username": "Rui",
                "isEdit": false
            }
        },
        "lock": {}
    },
    {
        "num": 11,
        "color": "#fff",
        "btn": false,
        "borderRadius": 0,
        "tag": false,
        "fontsize": 14,
        "fontWeight": 400,
        "borderColor": "#5C5C5C",
        "link": false,
        "step": false,
        "sem": false,
        "cnt": false,
        "textColor": "black",
        "swi": false,
        "pag": false,
        "scr": false,
        "web": false,
        "sli": false,
        "seen": true,
        "sc": false,
        "mc": false,
        "sel": false,
        "top": "10px",
        "left": "10px",
        "opacity": 100,
        "delSeen": false,
        "borderExists": true,
        "border": "",
        "word": false,
        "borderWidth": 1,
        "z_index": 10,
        "pic": 0,
        "w": 190,
        "h": 230,
        "x": 570,
        "y": 260,
        "dragging": "onDrag",
        "resizing": "onResize",
        "parent": true,
        "class": "square",
        "handles": [
            "tl",
            "tr",
            "bl",
            "br"
        ],
        "editingUsers": {
            "72": {
                "username": "Rui",
                "isEdit": false
            }
        },
        "lock": {}
    },
    {
        "num": 12,
        "color": null,
        "textColor": "black",
        "fontWeight": 800,
        "borderRadius": 0,
        "seen": true,
        "borderColor": "black",
        "top": "10px",
        "link": false,
        "sem": false,
        "fontsize": 16,
        "cnt": false,
        "step": false,
        "pag": false,
        "web": false,
        "tag": false,
        "sli": false,
        "swi": false,
        "sc": false,
        "scr": false,
        "mc": false,
        "sel": false,
        "left": "10px",
        "opacity": 100,
        "btn": false,
        "delSeen": false,
        "borderExists": false,
        "border": "none",
        "borderWidth": 1,
        "word": true,
        "text": "Top Author",
        "z_index": 11,
        "w": 120,
        "h": 30,
        "x": 119,
        "y": 265,
        "dragging": "onDrag",
        "resizing": "onResize",
        "parent": true,
        "class": "word",
        "handles": [
            "tl",
            "tr",
            "bl",
            "br"
        ],
        "editingUsers": {
            "72": {
                "username": "Rui",
                "isEdit": false
            }
        },
        "lock": {}
    },
    {
        "num": 13,
        "color": null,
        "textColor": "#000000",
        "fontWeight": 600,
        "borderRadius": 0,
        "seen": true,
        "borderColor": null,
        "top": "10px",
        "link": false,
        "sem": false,
        "fontsize": 16,
        "cnt": false,
        "step": false,
        "pag": false,
        "web": false,
        "tag": false,
        "sli": false,
        "swi": false,
        "sc": false,
        "scr": false,
        "mc": false,
        "sel": false,
        "left": "10px",
        "opacity": 100,
        "btn": false,
        "delSeen": false,
        "borderExists": false,
        "border": "none",
        "borderWidth": 1,
        "word": true,
        "text": "Top Journal",
        "z_index": 12,
        "w": 120,
        "h": 30,
        "x": 349,
        "y": 265,
        "dragging": "onDrag",
        "resizing": "onResize",
        "parent": true,
        "class": "word",
        "handles": [
            "tl",
            "tr",
            "bl",
            "br"
        ],
        "editingUsers": {
            "72": {
                "username": "Rui",
                "isEdit": false
            }
        },
        "lock": {}
    },
    {
        "num": 14,
        "color": null,
        "textColor": "black",
        "fontWeight": 600,
        "borderRadius": 0,
        "seen": true,
        "borderColor": "black",
        "top": "10px",
        "link": false,
        "sem": false,
        "fontsize": 14,
        "cnt": false,
        "step": false,
        "pag": false,
        "web": false,
        "tag": false,
        "sli": false,
        "swi": false,
        "sc": false,
        "scr": false,
        "mc": false,
        "sel": false,
        "left": "10px",
        "opacity": 100,
        "btn": false,
        "delSeen": false,
        "borderExists": false,
        "border": "none",
        "borderWidth": 1,
        "word": true,
        "text": "Top Conference",
        "z_index": 13,
        "w": 120,
        "h": 28,
        "x": 580,
        "y": 265,
        "dragging": "onDrag",
        "resizing": "onResize",
        "parent": true,
        "class": "word",
        "handles": [
            "tl",
            "tr",
            "bl",
            "br"
        ],
        "editingUsers": {
            "72": {
                "username": "Rui",
                "isEdit": false
            }
        },
        "lock": {}
    },
    {
        "num": 15,
        "color": null,
        "btn": false,
        "borderRadius": 0,
        "borderColor": "black",
        "fontWeight": 400,
        "tag": false,
        "fontsize": 14,
        "link": true,
        "step": false,
        "sem": false,
        "cnt": false,
        "textColor": "black",
        "swi": false,
        "pag": false,
        "scr": false,
        "web": false,
        "content": "aaa",
        "sli": false,
        "seen": false,
        "url": "",
        "sc": false,
        "mc": false,
        "sel": false,
        "top": "10px",
        "left": "10px",
        "opacity": 100,
        "delSeen": true,
        "borderExists": false,
        "border": "none",
        "word": false,
        "borderWidth": 1,
        "z_index": 14,
        "pic": 0,
        "w": 80,
        "h": 50,
        "x": 90,
        "y": 552,
        "dragging": "onDrag",
        "resizing": "onResize",
        "parent": true,
        "class": "square",
        "handles": [
            "tl",
            "tr",
            "bl",
            "br"
        ],
        "editingUsers": {
            "72": {
                "username": "Rui",
                "isEdit": true
            }
        },
        "lock": {}
    }
]
}
export default debugArr